# Generated by Django 5.1.6 on 2025-03-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alumniprofile_chatmessage_event_jobpost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='company_name',
            new_name='company',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='alumni',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='apply_link',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='location',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='posted_on',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='title',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='application_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_name',
            field=models.CharField(default='Unnamed Job', max_length=100),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time')], default=4, max_length=100),
        ),
    ]
