# Generated by Django 5.1.6 on 2025-03-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_user_user_type_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('alumni', 'Alumni'), ('student', 'Student')], default='student', max_length=10),
        ),
    ]
