# Generated by Django 5.1.6 on 2025-04-08 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alumniprofile_department_alumniprofile_passout_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='posted_by',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
