# Generated by Django 5.1.6 on 2025-04-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_jobpost_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprofile',
            name='passout_year',
            field=models.IntegerField(default=2025),
        ),
    ]
