# Generated by Django 5.1.6 on 2025-04-24 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_connection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Connection',
        ),
    ]
