# Generated by Django 5.1.6 on 2025-04-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_connection_delete_connectionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
