# Generated by Django 5.1.6 on 2025-05-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
