# Generated by Django 5.1.6 on 2025-05-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_jobpost_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='department',
            field=models.CharField(choices=[('it', 'Information Technology'), ('cs', 'Computer Science'), ('me', 'Mechanical Engineering'), ('ec', 'Electronics Engineering'), ('ee', 'Electrical Engineering')], default='Computer Science', max_length=20),
            preserve_default=False,
        ),
    ]
